on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: deploy to prod
    runs-on: self-hosted

    steps:
      - name: Clone repository
        uses: actions/checkout@v3.5.3

      - name: Run docker compose
        run: docker compose up --build --force-recreate -d
